# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\sheen\OneDrive\Desktop\StandardGui_3.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StandardCalc(object):
    def setupUi(self, StandardCalc):
        StandardCalc.setObjectName("StandardCalc")
        StandardCalc.resize(238, 395)
        StandardCalc.setMinimumSize(QtCore.QSize(238, 395))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Standard/images.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        StandardCalc.setWindowIcon(icon)
        StandardCalc.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));")
        self.centralwidget = QtWidgets.QWidget(StandardCalc)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 10, 231, 341))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_p1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_p1.setGeometry(QtCore.QRect(10, 100, 31, 31))
        self.pushButton_p1.setObjectName("pushButton_p1")
        self.pushButton_p2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_p2.setGeometry(QtCore.QRect(50, 100, 31, 31))
        self.pushButton_p2.setObjectName("pushButton_p2")
        self.pushButton_p4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_p4.setGeometry(QtCore.QRect(10, 150, 31, 31))
        self.pushButton_p4.setObjectName("pushButton_p4")
        self.pushButton_p3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_p3.setGeometry(QtCore.QRect(90, 100, 31, 31))
        self.pushButton_p3.setObjectName("pushButton_p3")
        self.pushButton_p6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_p6.setGeometry(QtCore.QRect(90, 150, 31, 31))
        self.pushButton_p6.setObjectName("pushButton_p6")
        self.pushButton_p5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_p5.setGeometry(QtCore.QRect(50, 150, 31, 31))
        self.pushButton_p5.setObjectName("pushButton_p5")
        self.pushButton_p9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_p9.setGeometry(QtCore.QRect(90, 200, 31, 31))
        self.pushButton_p9.setObjectName("pushButton_p9")
        self.pushButton_p8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_p8.setGeometry(QtCore.QRect(50, 200, 31, 31))
        self.pushButton_p8.setObjectName("pushButton_p8")
        self.pushButton_p7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_p7.setGeometry(QtCore.QRect(10, 200, 31, 31))
        self.pushButton_p7.setObjectName("pushButton_p7")
        self.pushButton_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_1.setGeometry(QtCore.QRect(190, 100, 31, 31))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_clearall = QtWidgets.QPushButton(self.frame)
        self.pushButton_clearall.setGeometry(QtCore.QRect(10, 50, 31, 31))
        self.pushButton_clearall.setObjectName("pushButton_clearall")
        self.pushButton_clear = QtWidgets.QPushButton(self.frame)
        self.pushButton_clear.setGeometry(QtCore.QRect(50, 50, 81, 31))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_root = QtWidgets.QPushButton(self.frame)
        self.pushButton_root.setGeometry(QtCore.QRect(140, 100, 31, 31))
        self.pushButton_root.setObjectName("pushButton_root")
        self.pushButton_add = QtWidgets.QPushButton(self.frame)
        self.pushButton_add.setGeometry(QtCore.QRect(140, 150, 31, 31))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_minus = QtWidgets.QPushButton(self.frame)
        self.pushButton_minus.setGeometry(QtCore.QRect(140, 200, 31, 31))
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_equals = QtWidgets.QPushButton(self.frame)
        self.pushButton_equals.setGeometry(QtCore.QRect(30, 290, 161, 31))
        self.pushButton_equals.setObjectName("pushButton_equals")
        self.pushButton_divide = QtWidgets.QPushButton(self.frame)
        self.pushButton_divide.setGeometry(QtCore.QRect(140, 50, 31, 31))
        self.pushButton_divide.setObjectName("pushButton_divide")
        self.pushButton_dot = QtWidgets.QPushButton(self.frame)
        self.pushButton_dot.setGeometry(QtCore.QRect(50, 240, 31, 31))
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.pushButton_times = QtWidgets.QPushButton(self.frame)
        self.pushButton_times.setGeometry(QtCore.QRect(90, 240, 31, 31))
        self.pushButton_times.setObjectName("pushButton_times")
        self.pushButton_square = QtWidgets.QPushButton(self.frame)
        self.pushButton_square.setGeometry(QtCore.QRect(140, 240, 31, 31))
        self.pushButton_square.setObjectName("pushButton_square")
        self.pushButton_p0 = QtWidgets.QPushButton(self.frame)
        self.pushButton_p0.setGeometry(QtCore.QRect(10, 240, 31, 31))
        self.pushButton_p0.setObjectName("pushButton_p0")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 191, 31))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton_sin = QtWidgets.QPushButton(self.frame)
        self.pushButton_sin.setGeometry(QtCore.QRect(190, 50, 31, 31))
        self.pushButton_sin.setObjectName("pushButton_sin")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame)
        self.pushButton_15.setGeometry(QtCore.QRect(190, 150, 31, 31))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame)
        self.pushButton_16.setGeometry(QtCore.QRect(190, 200, 31, 31))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.frame)
        self.pushButton_17.setGeometry(QtCore.QRect(190, 240, 31, 31))
        self.pushButton_17.setObjectName("pushButton_17")
        StandardCalc.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(StandardCalc)
        self.statusbar.setObjectName("statusbar")
        StandardCalc.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(StandardCalc)
        self.toolBar.setObjectName("toolBar")
        StandardCalc.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(StandardCalc)
        QtCore.QMetaObject.connectSlotsByName(StandardCalc)

    def retranslateUi(self, StandardCalc):
        _translate = QtCore.QCoreApplication.translate
        StandardCalc.setWindowTitle(_translate("StandardCalc", "Standard"))
        self.pushButton_p1.setText(_translate("StandardCalc", "1"))
        self.pushButton_p2.setText(_translate("StandardCalc", "2"))
        self.pushButton_p4.setText(_translate("StandardCalc", "4"))
        self.pushButton_p3.setText(_translate("StandardCalc", "3"))
        self.pushButton_p6.setText(_translate("StandardCalc", "6"))
        self.pushButton_p5.setText(_translate("StandardCalc", "5"))
        self.pushButton_p9.setText(_translate("StandardCalc", "9"))
        self.pushButton_p8.setText(_translate("StandardCalc", "8"))
        self.pushButton_p7.setText(_translate("StandardCalc", "7"))
        self.pushButton_1.setText(_translate("StandardCalc", "Cos"))
        self.pushButton_clearall.setText(_translate("StandardCalc", "CE"))
        self.pushButton_clear.setText(_translate("StandardCalc", "C"))
        self.pushButton_root.setText(_translate("StandardCalc", " √"))
        self.pushButton_add.setText(_translate("StandardCalc", "+"))
        self.pushButton_minus.setText(_translate("StandardCalc", "-"))
        self.pushButton_equals.setText(_translate("StandardCalc", "="))
        self.pushButton_divide.setText(_translate("StandardCalc", "÷"))
        self.pushButton_dot.setText(_translate("StandardCalc", "."))
        self.pushButton_times.setText(_translate("StandardCalc", "X"))
        self.pushButton_square.setText(_translate("StandardCalc", "x²"))
        self.pushButton_p0.setText(_translate("StandardCalc", "0"))
        self.pushButton_sin.setText(_translate("StandardCalc", "Sin"))
        self.pushButton_15.setText(_translate("StandardCalc", "Tan"))
        self.pushButton_16.setText(_translate("StandardCalc", "Ln"))
        self.pushButton_17.setText(_translate("StandardCalc", "Log"))
        self.toolBar.setWindowTitle(_translate("StandardCalc", "toolBar"))

import Standard_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StandardCalc = QtWidgets.QMainWindow()
    ui = Ui_StandardCalc()
    ui.setupUi(StandardCalc)
    StandardCalc.show()
    sys.exit(app.exec_())

